version: "3"
services:
  db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_PASSWORD: 123456
    volumes:
      - ./mysql_data:/var/lib/mysql

  redis:
    image: redis
    command: redis-server --requirepass 123456
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/data

  app_serv_green:
    build: .
    image: bptw/rails5:latest
    command: bundle exec rails server -p 3301 -b 0.0.0.0 --pid ./tmp/pids/green.pid -e development
    volumes:
      - ./rails_app:/rails_app:rw
    ports:
      - "3301:3301"
    depends_on:
      - db
      - redis
    env_file:
      - '.env'

  app_serv_blue:
    build: .
    image: bptw/rails5:latest
    command: bundle exec rails server -p 3302 -b 0.0.0.0 --pid ./tmp/pids/blue.pid -e development
    volumes:
      - ./rails_app:/rails_app:rw
    ports:
      - "3302:3302"
    depends_on:
      - db
      - redis
    env_file:
      - '.env'

  web_serv:
    image: nginx
    restart: always
    command: sh -c "cp /tmp/default.conf /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
     - ./nginx.template:/tmp/default.conf:ro
     - ./deploy/replace_nginx_template.sh:/tmp/replace_nginx_template.sh:ro
     - ./rails_app:/rails_app
    ports:
     - "8081:80"
    #depends_on:
     #- app_serv_green
     #- app_serv_blue
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80

  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    image: bptw/rails5:latest
    command: sidekiq -C ./config/sidekiq.yml -r /rails_app
    volumes:
      - ./rails_app:/rails_app
    env_file:
      - '.env'
